services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - /var/lib/db:/var/lib/mysql  # БД сохраняется на хосте

  freeradius:
    build:
      context: .
      dockerfile: Dockerfile.freeradius
    container_name: freeradius
    depends_on:
      - db
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    restart: unless-stopped
